apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gncsipfh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gncsipfh:87b70fba7d265eac8de50651fe80fd3c1647c26c@sha256:ab9c67d8dddec2966ef63c9c1a794b85484aa43a11d122d77e357ec4f07e3510
          name: container-image
